services:
  database:
    container_name: postgres_db
    image: postgres:13.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"

  web:
    container_name: web-app
    build: .
    command: >
      sh -c "alembic upgrade head"
    volumes:
      - .:/code
    environment:
       - DB_HOST=database
       - DB_PORT=5432
       - DB_NAME=postgres
       - DB_USER=postgres
       - DB_PASSWORD=postgres
    depends_on:
      - database
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - database
    links:
      - "database:db"
