"""empty message

Revision ID: 2ef41c5cd1c6
Revises: 2c5f48f21c7a
Create Date: 2023-09-03 15:38:34.857969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef41c5cd1c6'
down_revision: Union[str, None] = '2c5f48f21c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
